global.game_speed = 1;
ini_open("tower_defence.ini");
global.fase = ini_read_real("menu", "nivel", 1);
global.gold = ini_read_real("menu", "gold", 0);
global.visual1 = ini_read_real("monstro1", "visual", 1);
global.visual2 = ini_read_real("monstro2", "visual", 1);
global.visual3 = ini_read_real("monstro3", "visual", 2);
global.visual4 = ini_read_real("monstro4", "visual", 0);
global.visual5 = ini_read_real("monstro5", "visual", 0);
ini_close();
room_goto(scn_mapa);