/// @description Inserir descrição aqui
// Você pode escrever seu código neste editor



// Inherit the parent event
event_inherited();

spriteIdle = sPlayer2;
spriteWalk = sPlayer2Walking;

scene_info[0] = [
	[cutscene_switched_page, 1, true, 2],
	[cutscene_section_start, true, true],
	
	[cutscene_wait, 50],
	[balloon, balloon_Duvida, global.player, true, 0, true],
	[cutscene_wait, 50],
	
	[cutscene_change_graphic, global.player,spriteWalk],
	[cutscene_move_anim,"up", 5, 40,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_change_graphic, global.player,spriteIdle],

	[cutscene_look_direction, global.player,1],
	[bubble_speech,global.player,"Scobby-Dubby-Dooo", "Hanna Barberta", 1, 0, global.config.textcolor, c_olive],
	
	[cutscene_change_graphic, global.player,spriteWalk, 1],
	[cutscene_move_anim,"downright", 2, 85,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_change_graphic, global.player,spriteIdle],
	
	[cutscene_wait, 60],
	[cutscene_look_direction,global.player,-1],
	[cutscene_wait, 60],
	[cutscene_look_direction,global.player,1],
	[cutscene_wait, 60],
	[cutscene_look_direction,global.player,-1],
	[cutscene_wait, 60],
	
	[cutscene_move_anim,"left", 1, 120,spriteIdle,spriteWalk, 1, true, global.player],
	
	[cutscene_section_start, false, false],
	
	[cutscene_wait, 60],
	[bubble_speech,global.player,"moonwalkin", "Maicu Jaksu", 1, 0, global.config.textcolor, c_olive],
	
	[cutscene_wait, 60],
	[cutscene_move_anim,"right", 2, 90,spriteIdle,spriteWalk, -1, true, global.player],
	[cutscene_move_anim,"left", 2, 30,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_move_anim,"right", 2, 5,spriteIdle,spriteWalk, -1, true, global.player],
	[cutscene_move_anim,"left", 2, 4,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_move_anim,"right", 2, 6,spriteIdle,spriteWalk, -1, true, global.player],
	[cutscene_move_anim,"left", 2, 3,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_move_anim,"right", 2, 6,spriteIdle,spriteWalk, -1, true, global.player],
	[cutscene_move_anim,"left", 2, 7,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_move_anim,"right", 2, 6,spriteIdle,spriteWalk, -1, true, global.player],
	[cutscene_move_anim,"left", 2, 15,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_move_anim,"right", 2, 7,spriteIdle,spriteWalk, -1, true, global.player],
	[cutscene_move_anim,"left", 2, 5,spriteIdle,spriteWalk, 1, true, global.player],
	[cutscene_change_graphic, global.player,spriteIdle],
	
	[bubble_speech,global.player,"AU!", "Maicu Jaksu", 1, 0, global.config.textcolor, c_olive],
	
	[cutscene_wait, 60],
	[bubble_speech,global.player,"melhor não esquentar a cabeça se não cai o cabelo", "", 1, 0, global.config.textcolor, c_olive],
	[cutscene_wait, 60],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_wait, 5],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_wait, 7],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_wait, 3],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_wait, 15],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_change_graphic, global.player, HannaProv1],
	[cutscene_wait, 30],
	
	[bubble_speech,global.player,"tive dejavus de mim careca!", "", 1, 0, global.config.textcolor, c_olive],
	[cutscene_wait, 60],
	[bubble_speech,global.player,"musquitão da dengue, tem que matar", "Drauzio Varella", 1, 0, global.config.textcolor, c_olive],
	[balloon, balloon_waiting, global.player, true, 0, true],
	[cutscene_wait, 60],
	[bubble_speech,global.player,"é verdade!", "Drauzio Varella", 1, 0, global.config.textcolor, c_olive],
	[bubble_speech,global.player,"quer dizer, as vezes não", "Drauzio Varella", 1, 0, global.config.textcolor, c_olive],
	[cutscene_reset()], 
]
